2022-05-16 20:24:44,469 [INFO] root consoleworker.py:434	Log file created
2022-05-16 20:24:44,471 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x40192a2c10> added
2022-05-16 20:24:44,471 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x401926a850> added
2022-05-16 20:24:44,472 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x401928ea50> added
2022-05-16 20:24:44,474 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2022-05-16_20-24-44.292749
2022-05-16 20:24:44,475 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2022-05-16 20:24:44,478 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2022-05-16 20:24:44,481 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2022-05-16 20:24:44,485 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2022-05-16 20:24:44,487 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2022-05-16 20:24:44,495 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2022-05-16 20:24:44,498 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2022-05-16 20:24:44,500 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2022-05-16 20:24:44,501 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2022-05-16 20:24:44,502 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2022-05-16 20:24:44,503 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x401959fc90>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x40195b1710>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x40195b1650>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x40195b1410>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x40195b1290>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x401959f910>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x401959ff90>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x401920aa10>}
2022-05-16 20:24:44,504 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x401959fc90>
2022-05-16 20:24:44,506 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2022-05-16 20:24:44,518 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-44.292749/answ_UUuf0x.log
2022-05-16 20:24:44,524 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-44.292749/phout_gVh8YJ.log
2022-05-16 20:24:44,525 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_stat_HZ01OG.log
2022-05-16 20:24:44,529 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_Mmc24F.log
2022-05-16 20:24:44,532 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 0.0.0.0:8080
2022-05-16 20:24:44,536 [DEBUG] yandextank.common.util util.py:516	Parsing port
2022-05-16 20:24:44,538 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('0.0.0.0', 8080)), (2, 2, 17, '', ('0.0.0.0', 8080)), (2, 3, 0, '', ('0.0.0.0', 8080))]
2022-05-16 20:24:44,539 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:44,544 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:44,545 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:44,547 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:44,549 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:44,552 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:44,553 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:44,554 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:44,555 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:44,556 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:44,558 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:44,559 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:44,566 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 0.0.0.0, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2022-05-16 20:24:44,590 [INFO] root consoleworker.py:269	Trying to clean up
2022-05-16 20:24:44,592 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_IrVvPv.lock
2022-05-16 20:24:44,604 [WARNING] root consoleworker.py:408	Job number is not available yet
2022-05-16 20:24:44,606 [WARNING] root consoleworker.py:415	Job number is not available yet
2022-05-16 20:24:44,622 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2022-05-16 20:24:44,623 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2022-05-16_20-24-44.292749
2022-05-16 20:24:44,624 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-44.292749/phout_gVh8YJ.log to /var/loadtest/logs/2022-05-16_20-24-44.292749/phout_gVh8YJ.log
2022-05-16 20:24:44,626 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-44.292749/phout_gVh8YJ.log
2022-05-16 20:24:44,629 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_Mmc24F.log to /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_Mmc24F.log
2022-05-16 20:24:44,632 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_Mmc24F.log
2022-05-16 20:24:44,635 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2022-05-16_20-24-44.292749/validation_error.yaml
2022-05-16 20:24:44,636 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2022-05-16 20:24:44,638 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-44.292749/answ_UUuf0x.log to /var/loadtest/logs/2022-05-16_20-24-44.292749/answ_UUuf0x.log
2022-05-16 20:24:44,639 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-44.292749/answ_UUuf0x.log
2022-05-16 20:24:44,641 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_stat_HZ01OG.log to /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_stat_HZ01OG.log
2022-05-16 20:24:44,643 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-44.292749/phantom_stat_HZ01OG.log
