2022-05-16 20:24:00,555 [INFO] root consoleworker.py:434	Log file created
2022-05-16 20:24:00,557 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x40192a2c10> added
2022-05-16 20:24:00,558 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x401926a850> added
2022-05-16 20:24:00,560 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x401928ea50> added
2022-05-16 20:24:00,562 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2022-05-16_20-24-00.154217
2022-05-16 20:24:00,564 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2022-05-16 20:24:00,566 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2022-05-16 20:24:00,569 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2022-05-16 20:24:00,572 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2022-05-16 20:24:00,574 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2022-05-16 20:24:00,618 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2022-05-16 20:24:00,632 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2022-05-16 20:24:00,639 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2022-05-16 20:24:00,643 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2022-05-16 20:24:00,648 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2022-05-16 20:24:00,652 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x401959ff50>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x40195b11d0>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x40195b10d0>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x40195b1050>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x40195b12d0>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x401959fe50>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x401959fb10>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x401920aa10>}
2022-05-16 20:24:00,659 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x401959ff50>
2022-05-16 20:24:00,664 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2022-05-16 20:24:00,697 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-00.154217/answ_yO4zo9.log
2022-05-16 20:24:00,715 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-00.154217/phout_P7DrEi.log
2022-05-16 20:24:00,719 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_stat_tvwK33.log
2022-05-16 20:24:00,738 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_O3oYY2.log
2022-05-16 20:24:00,747 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 0.0.0.0:8080
2022-05-16 20:24:00,766 [DEBUG] yandextank.common.util util.py:516	Parsing port
2022-05-16 20:24:00,769 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('0.0.0.0', 8080)), (2, 2, 17, '', ('0.0.0.0', 8080)), (2, 3, 0, '', ('0.0.0.0', 8080))]
2022-05-16 20:24:00,771 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:00,778 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:00,780 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:00,781 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:00,783 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:00,785 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:00,786 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:00,787 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:00,788 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 0.0.0.0 and port 8080
2022-05-16 20:24:00,791 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [0.0.0.0]:8080 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2022-05-16 20:24:00,792 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [0.0.0.0]:8080
2022-05-16 20:24:00,793 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [0.0.0.0]:8080
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [0.0.0.0]:8080, use phantom.connection_test=0 to disable it
2022-05-16 20:24:00,797 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 0.0.0.0, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2022-05-16 20:24:00,801 [INFO] root consoleworker.py:269	Trying to clean up
2022-05-16 20:24:00,803 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_SpMk6w.lock
2022-05-16 20:24:00,808 [WARNING] root consoleworker.py:408	Job number is not available yet
2022-05-16 20:24:00,810 [WARNING] root consoleworker.py:415	Job number is not available yet
2022-05-16 20:24:00,826 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2022-05-16 20:24:00,833 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2022-05-16_20-24-00.154217
2022-05-16 20:24:00,835 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-00.154217/phout_P7DrEi.log to /var/loadtest/logs/2022-05-16_20-24-00.154217/phout_P7DrEi.log
2022-05-16 20:24:00,837 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-00.154217/phout_P7DrEi.log
2022-05-16 20:24:00,841 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-00.154217/answ_yO4zo9.log to /var/loadtest/logs/2022-05-16_20-24-00.154217/answ_yO4zo9.log
2022-05-16 20:24:00,843 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-00.154217/answ_yO4zo9.log
2022-05-16 20:24:00,846 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2022-05-16_20-24-00.154217/validation_error.yaml
2022-05-16 20:24:00,850 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2022-05-16 20:24:00,854 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_stat_tvwK33.log to /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_stat_tvwK33.log
2022-05-16 20:24:00,856 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_stat_tvwK33.log
2022-05-16 20:24:00,859 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_O3oYY2.log to /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_O3oYY2.log
2022-05-16 20:24:00,860 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2022-05-16_20-24-00.154217/phantom_O3oYY2.log
